<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

// Kelas CountrySeeder: country seeder
class CountrySeeder extends Seeder
{
    // run
    public function run()
    {
        $count = 0;
        foreach ($this->countries() as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
            $count++;
        }

        $this->command?->info("CountrySeeder: {$count} negara berhasil di-seed.");
    }

    
    // countries
    protected function countries(): array
    {
        return [
            
            ['name' => 'Algeria', 'code' => 'DZ', 'capital' => 'Algiers', 'currency' => 'DZD', 'currency_symbol' => 'د.ج', 'latitude' => 36.7538, 'longitude' => 3.0588],
            ['name' => 'Angola', 'code' => 'AO', 'capital' => 'Luanda', 'currency' => 'AOA', 'currency_symbol' => 'Kz', 'latitude' => -8.839, 'longitude' => 13.2894],
            ['name' => 'Benin', 'code' => 'BJ', 'capital' => 'Porto-Novo', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'latitude' => 6.4969, 'longitude' => 2.6289],
            ['name' => 'Botswana', 'code' => 'BW', 'capital' => 'Gaborone', 'currency' => 'BWP', 'currency_symbol' => 'P', 'latitude' => -24.6282, 'longitude' => 25.9231],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'capital' => 'Ouagadougou', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'latitude' => 12.3714, 'longitude' => -1.5197],
            ['name' => 'Burundi', 'code' => 'BI', 'capital' => 'Gitega', 'currency' => 'BIF', 'currency_symbol' => 'FBu', 'latitude' => -3.4264, 'longitude' => 29.9306],
            ['name' => 'Cabo Verde', 'code' => 'CV', 'capital' => 'Praia', 'currency' => 'CVE', 'currency_symbol' => '$', 'latitude' => 14.933, 'longitude' => -23.5133],
            ['name' => 'Cameroon', 'code' => 'CM', 'capital' => 'Yaoundé', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'latitude' => 3.848, 'longitude' => 11.5021],
            ['name' => 'Central African Republic', 'code' => 'CF', 'capital' => 'Bangui', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'latitude' => 4.3947, 'longitude' => 18.5582],
            ['name' => 'Chad', 'code' => 'TD', 'capital' => "N'Djamena", 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'latitude' => 12.1348, 'longitude' => 15.0557],
            ['name' => 'Comoros', 'code' => 'KM', 'capital' => 'Moroni', 'currency' => 'KMF', 'currency_symbol' => 'CF', 'latitude' => -11.7042, 'longitude' => 43.2402],
            ['name' => 'Republic of the Congo', 'code' => 'CG', 'capital' => 'Brazzaville', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'latitude' => -4.2634, 'longitude' => 15.2429],
            ['name' => 'DR Congo', 'code' => 'CD', 'capital' => 'Kinshasa', 'currency' => 'CDF', 'currency_symbol' => 'FC', 'latitude' => -4.4419, 'longitude' => 15.2663],
            ['name' => "Cote d'Ivoire", 'code' => 'CI', 'capital' => 'Yamoussoukro', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'latitude' => 6.8276, 'longitude' => -5.2893],
            ['name' => 'Djibouti', 'code' => 'DJ', 'capital' => 'Djibouti', 'currency' => 'DJF', 'currency_symbol' => 'Fdj', 'latitude' => 11.5721, 'longitude' => 43.1456],
            ['name' => 'Egypt', 'code' => 'EG', 'capital' => 'Cairo', 'currency' => 'EGP', 'currency_symbol' => 'E£', 'latitude' => 30.0444, 'longitude' => 31.2357],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'capital' => 'Malabo', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'latitude' => 3.7523, 'longitude' => 8.7742],
            ['name' => 'Eritrea', 'code' => 'ER', 'capital' => 'Asmara', 'currency' => 'ERN', 'currency_symbol' => 'Nfk', 'latitude' => 15.3229, 'longitude' => 38.9251],
            ['name' => 'Eswatini', 'code' => 'SZ', 'capital' => 'Mbabane', 'currency' => 'SZL', 'currency_symbol' => 'L', 'latitude' => -26.3054, 'longitude' => 31.1367],
            ['name' => 'Ethiopia', 'code' => 'ET', 'capital' => 'Addis Ababa', 'currency' => 'ETB', 'currency_symbol' => 'Br', 'latitude' => 9.03, 'longitude' => 38.74],
            ['name' => 'Gabon', 'code' => 'GA', 'capital' => 'Libreville', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'latitude' => 0.4162, 'longitude' => 9.4673],
            ['name' => 'Gambia', 'code' => 'GM', 'capital' => 'Banjul', 'currency' => 'GMD', 'currency_symbol' => 'D', 'latitude' => 13.4531, 'longitude' => -16.5775],
            ['name' => 'Ghana', 'code' => 'GH', 'capital' => 'Accra', 'currency' => 'GHS', 'currency_symbol' => '₵', 'latitude' => 5.6037, 'longitude' => -0.187],
            ['name' => 'Guinea', 'code' => 'GN', 'capital' => 'Conakry', 'currency' => 'GNF', 'currency_symbol' => 'FG', 'latitude' => 9.6412, 'longitude' => -13.5784],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'capital' => 'Bissau', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'latitude' => 11.8817, 'longitude' => -15.6178],
            ['name' => 'Kenya', 'code' => 'KE', 'capital' => 'Nairobi', 'currency' => 'KES', 'currency_symbol' => 'KSh', 'latitude' => -1.2921, 'longitude' => 36.8219],
            ['name' => 'Lesotho', 'code' => 'LS', 'capital' => 'Maseru', 'currency' => 'LSL', 'currency_symbol' => 'L', 'latitude' => -29.3167, 'longitude' => 27.4833],
            ['name' => 'Liberia', 'code' => 'LR', 'capital' => 'Monrovia', 'currency' => 'LRD', 'currency_symbol' => '$', 'latitude' => 6.3005, 'longitude' => -10.7969],
            ['name' => 'Libya', 'code' => 'LY', 'capital' => 'Tripoli', 'currency' => 'LYD', 'currency_symbol' => 'ل.د', 'latitude' => 32.8872, 'longitude' => 13.1913],
            ['name' => 'Madagascar', 'code' => 'MG', 'capital' => 'Antananarivo', 'currency' => 'MGA', 'currency_symbol' => 'Ar', 'latitude' => -18.8792, 'longitude' => 47.5079],
            ['name' => 'Malawi', 'code' => 'MW', 'capital' => 'Lilongwe', 'currency' => 'MWK', 'currency_symbol' => 'MK', 'latitude' => -13.9626, 'longitude' => 33.7741],
            ['name' => 'Mali', 'code' => 'ML', 'capital' => 'Bamako', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'latitude' => 12.6392, 'longitude' => -8.0029],
            ['name' => 'Mauritania', 'code' => 'MR', 'capital' => 'Nouakchott', 'currency' => 'MRU', 'currency_symbol' => 'UM', 'latitude' => 18.0735, 'longitude' => -15.9582],
            ['name' => 'Mauritius', 'code' => 'MU', 'capital' => 'Port Louis', 'currency' => 'MUR', 'currency_symbol' => '₨', 'latitude' => -20.1609, 'longitude' => 57.5012],
            ['name' => 'Morocco', 'code' => 'MA', 'capital' => 'Rabat', 'currency' => 'MAD', 'currency_symbol' => 'د.م.', 'latitude' => 34.0209, 'longitude' => -6.8416],
            ['name' => 'Mozambique', 'code' => 'MZ', 'capital' => 'Maputo', 'currency' => 'MZN', 'currency_symbol' => 'MT', 'latitude' => -25.9692, 'longitude' => 32.5732],
            ['name' => 'Namibia', 'code' => 'NA', 'capital' => 'Windhoek', 'currency' => 'NAD', 'currency_symbol' => '$', 'latitude' => -22.5609, 'longitude' => 17.0658],
            ['name' => 'Niger', 'code' => 'NE', 'capital' => 'Niamey', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'latitude' => 13.5127, 'longitude' => 2.1128],
            ['name' => 'Nigeria', 'code' => 'NG', 'capital' => 'Abuja', 'currency' => 'NGN', 'currency_symbol' => '₦', 'latitude' => 9.0765, 'longitude' => 7.3986],
            ['name' => 'Rwanda', 'code' => 'RW', 'capital' => 'Kigali', 'currency' => 'RWF', 'currency_symbol' => 'FRw', 'latitude' => -1.9403, 'longitude' => 29.8739],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'capital' => 'Sao Tome', 'currency' => 'STN', 'currency_symbol' => 'Db', 'latitude' => 0.3365, 'longitude' => 6.7273],
            ['name' => 'Senegal', 'code' => 'SN', 'capital' => 'Dakar', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'latitude' => 14.7167, 'longitude' => -17.4677],
            ['name' => 'Seychelles', 'code' => 'SC', 'capital' => 'Victoria', 'currency' => 'SCR', 'currency_symbol' => '₨', 'latitude' => -4.6191, 'longitude' => 55.4513],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'capital' => 'Freetown', 'currency' => 'SLE', 'currency_symbol' => 'Le', 'latitude' => 8.4657, 'longitude' => -13.2317],
            ['name' => 'Somalia', 'code' => 'SO', 'capital' => 'Mogadishu', 'currency' => 'SOS', 'currency_symbol' => 'S', 'latitude' => 2.0469, 'longitude' => 45.3182],
            ['name' => 'South Africa', 'code' => 'ZA', 'capital' => 'Pretoria', 'currency' => 'ZAR', 'currency_symbol' => 'R', 'latitude' => -25.7461, 'longitude' => 28.1881],
            ['name' => 'South Sudan', 'code' => 'SS', 'capital' => 'Juba', 'currency' => 'SSP', 'currency_symbol' => '£', 'latitude' => 4.8517, 'longitude' => 31.5825],
            ['name' => 'Sudan', 'code' => 'SD', 'capital' => 'Khartoum', 'currency' => 'SDG', 'currency_symbol' => 'ج.س.', 'latitude' => 15.5007, 'longitude' => 32.5599],
            ['name' => 'Tanzania', 'code' => 'TZ', 'capital' => 'Dodoma', 'currency' => 'TZS', 'currency_symbol' => 'TSh', 'latitude' => -6.163, 'longitude' => 35.7516],
            ['name' => 'Togo', 'code' => 'TG', 'capital' => 'Lomé', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'latitude' => 6.1725, 'longitude' => 1.2314],
            ['name' => 'Tunisia', 'code' => 'TN', 'capital' => 'Tunis', 'currency' => 'TND', 'currency_symbol' => 'د.ت', 'latitude' => 36.8065, 'longitude' => 10.1815],
            ['name' => 'Uganda', 'code' => 'UG', 'capital' => 'Kampala', 'currency' => 'UGX', 'currency_symbol' => 'USh', 'latitude' => 0.3476, 'longitude' => 32.5825],
            ['name' => 'Zambia', 'code' => 'ZM', 'capital' => 'Lusaka', 'currency' => 'ZMW', 'currency_symbol' => 'ZK', 'latitude' => -15.3875, 'longitude' => 28.3228],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'capital' => 'Harare', 'currency' => 'ZWL', 'currency_symbol' => '$', 'latitude' => -17.8292, 'longitude' => 31.0522],

            
            ['name' => 'Afghanistan', 'code' => 'AF', 'capital' => 'Kabul', 'currency' => 'AFN', 'currency_symbol' => '؋', 'latitude' => 34.5553, 'longitude' => 69.2075],
            ['name' => 'Armenia', 'code' => 'AM', 'capital' => 'Yerevan', 'currency' => 'AMD', 'currency_symbol' => '֏', 'latitude' => 40.1792, 'longitude' => 44.4991],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'capital' => 'Baku', 'currency' => 'AZN', 'currency_symbol' => '₼', 'latitude' => 40.4093, 'longitude' => 49.8671],
            ['name' => 'Bahrain', 'code' => 'BH', 'capital' => 'Manama', 'currency' => 'BHD', 'currency_symbol' => '.د.ب', 'latitude' => 26.2285, 'longitude' => 50.586],
            ['name' => 'Bangladesh', 'code' => 'BD', 'capital' => 'Dhaka', 'currency' => 'BDT', 'currency_symbol' => '৳', 'latitude' => 23.8103, 'longitude' => 90.4125],
            ['name' => 'Bhutan', 'code' => 'BT', 'capital' => 'Thimphu', 'currency' => 'BTN', 'currency_symbol' => 'Nu.', 'latitude' => 27.4712, 'longitude' => 89.6386],
            ['name' => 'Brunei', 'code' => 'BN', 'capital' => 'Bandar Seri Begawan', 'currency' => 'BND', 'currency_symbol' => '$', 'latitude' => 4.9031, 'longitude' => 114.9398],
            ['name' => 'Cambodia', 'code' => 'KH', 'capital' => 'Phnom Penh', 'currency' => 'KHR', 'currency_symbol' => '៛', 'latitude' => 11.5564, 'longitude' => 104.9282],
            ['name' => 'China', 'code' => 'CN', 'capital' => 'Beijing', 'currency' => 'CNY', 'currency_symbol' => '¥', 'latitude' => 39.9042, 'longitude' => 116.4074],
            ['name' => 'Cyprus', 'code' => 'CY', 'capital' => 'Nicosia', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 35.1856, 'longitude' => 33.3823],
            ['name' => 'Georgia', 'code' => 'GE', 'capital' => 'Tbilisi', 'currency' => 'GEL', 'currency_symbol' => '₾', 'latitude' => 41.7151, 'longitude' => 44.8271],
            ['name' => 'India', 'code' => 'IN', 'capital' => 'New Delhi', 'currency' => 'INR', 'currency_symbol' => '₹', 'latitude' => 28.6139, 'longitude' => 77.209],
            ['name' => 'Indonesia', 'code' => 'ID', 'capital' => 'Jakarta', 'currency' => 'IDR', 'currency_symbol' => 'Rp', 'latitude' => -6.2088, 'longitude' => 106.8456],
            ['name' => 'Iran', 'code' => 'IR', 'capital' => 'Tehran', 'currency' => 'IRR', 'currency_symbol' => '﷼', 'latitude' => 35.6892, 'longitude' => 51.389],
            ['name' => 'Iraq', 'code' => 'IQ', 'capital' => 'Baghdad', 'currency' => 'IQD', 'currency_symbol' => 'ع.د', 'latitude' => 33.3152, 'longitude' => 44.3661],
            ['name' => 'Israel', 'code' => 'IL', 'capital' => 'Jerusalem', 'currency' => 'ILS', 'currency_symbol' => '₪', 'latitude' => 31.7683, 'longitude' => 35.2137],
            ['name' => 'Japan', 'code' => 'JP', 'capital' => 'Tokyo', 'currency' => 'JPY', 'currency_symbol' => '¥', 'latitude' => 35.6762, 'longitude' => 139.6503],
            ['name' => 'Jordan', 'code' => 'JO', 'capital' => 'Amman', 'currency' => 'JOD', 'currency_symbol' => 'د.ا', 'latitude' => 31.9454, 'longitude' => 35.9284],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'capital' => 'Astana', 'currency' => 'KZT', 'currency_symbol' => '₸', 'latitude' => 51.1694, 'longitude' => 71.4491],
            ['name' => 'Kuwait', 'code' => 'KW', 'capital' => 'Kuwait City', 'currency' => 'KWD', 'currency_symbol' => 'د.ك', 'latitude' => 29.3759, 'longitude' => 47.9774],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'capital' => 'Bishkek', 'currency' => 'KGS', 'currency_symbol' => 'с', 'latitude' => 42.8746, 'longitude' => 74.5698],
            ['name' => 'Laos', 'code' => 'LA', 'capital' => 'Vientiane', 'currency' => 'LAK', 'currency_symbol' => '₭', 'latitude' => 17.9757, 'longitude' => 102.6331],
            ['name' => 'Lebanon', 'code' => 'LB', 'capital' => 'Beirut', 'currency' => 'LBP', 'currency_symbol' => 'ل.ل', 'latitude' => 33.8938, 'longitude' => 35.5018],
            ['name' => 'Malaysia', 'code' => 'MY', 'capital' => 'Kuala Lumpur', 'currency' => 'MYR', 'currency_symbol' => 'RM', 'latitude' => 3.139, 'longitude' => 101.6869],
            ['name' => 'Maldives', 'code' => 'MV', 'capital' => 'Malé', 'currency' => 'MVR', 'currency_symbol' => '.ރ', 'latitude' => 4.1755, 'longitude' => 73.5093],
            ['name' => 'Mongolia', 'code' => 'MN', 'capital' => 'Ulaanbaatar', 'currency' => 'MNT', 'currency_symbol' => '₮', 'latitude' => 47.8864, 'longitude' => 106.9057],
            ['name' => 'Myanmar', 'code' => 'MM', 'capital' => 'Naypyidaw', 'currency' => 'MMK', 'currency_symbol' => 'K', 'latitude' => 19.7633, 'longitude' => 96.0785],
            ['name' => 'Nepal', 'code' => 'NP', 'capital' => 'Kathmandu', 'currency' => 'NPR', 'currency_symbol' => '₨', 'latitude' => 27.7172, 'longitude' => 85.324],
            ['name' => 'North Korea', 'code' => 'KP', 'capital' => 'Pyongyang', 'currency' => 'KPW', 'currency_symbol' => '₩', 'latitude' => 39.0392, 'longitude' => 125.7625],
            ['name' => 'Oman', 'code' => 'OM', 'capital' => 'Muscat', 'currency' => 'OMR', 'currency_symbol' => 'ر.ع.', 'latitude' => 23.588, 'longitude' => 58.3829],
            ['name' => 'Pakistan', 'code' => 'PK', 'capital' => 'Islamabad', 'currency' => 'PKR', 'currency_symbol' => '₨', 'latitude' => 33.6844, 'longitude' => 73.0479],
            ['name' => 'Palestine', 'code' => 'PS', 'capital' => 'Ramallah', 'currency' => 'ILS', 'currency_symbol' => '₪', 'latitude' => 31.9038, 'longitude' => 35.2034],
            ['name' => 'Philippines', 'code' => 'PH', 'capital' => 'Manila', 'currency' => 'PHP', 'currency_symbol' => '₱', 'latitude' => 14.5995, 'longitude' => 120.9842],
            ['name' => 'Qatar', 'code' => 'QA', 'capital' => 'Doha', 'currency' => 'QAR', 'currency_symbol' => 'ر.ق', 'latitude' => 25.2854, 'longitude' => 51.531],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'capital' => 'Riyadh', 'currency' => 'SAR', 'currency_symbol' => 'ر.س', 'latitude' => 24.7136, 'longitude' => 46.6753],
            ['name' => 'Singapore', 'code' => 'SG', 'capital' => 'Singapore', 'currency' => 'SGD', 'currency_symbol' => 'S$', 'latitude' => 1.3521, 'longitude' => 103.8198],
            ['name' => 'South Korea', 'code' => 'KR', 'capital' => 'Seoul', 'currency' => 'KRW', 'currency_symbol' => '₩', 'latitude' => 37.5665, 'longitude' => 126.978],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'capital' => 'Colombo', 'currency' => 'LKR', 'currency_symbol' => '₨', 'latitude' => 6.9271, 'longitude' => 79.8612],
            ['name' => 'Syria', 'code' => 'SY', 'capital' => 'Damascus', 'currency' => 'SYP', 'currency_symbol' => '£', 'latitude' => 33.5138, 'longitude' => 36.2765],
            ['name' => 'Taiwan', 'code' => 'TW', 'capital' => 'Taipei', 'currency' => 'TWD', 'currency_symbol' => 'NT$', 'latitude' => 25.033, 'longitude' => 121.5654],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'capital' => 'Dushanbe', 'currency' => 'TJS', 'currency_symbol' => 'ЅМ', 'latitude' => 38.5598, 'longitude' => 68.787],
            ['name' => 'Thailand', 'code' => 'TH', 'capital' => 'Bangkok', 'currency' => 'THB', 'currency_symbol' => '฿', 'latitude' => 13.7563, 'longitude' => 100.5018],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'capital' => 'Dili', 'currency' => 'USD', 'currency_symbol' => '$', 'latitude' => -8.5569, 'longitude' => 125.5603],
            ['name' => 'Turkey', 'code' => 'TR', 'capital' => 'Ankara', 'currency' => 'TRY', 'currency_symbol' => '₺', 'latitude' => 39.9334, 'longitude' => 32.8597],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'capital' => 'Ashgabat', 'currency' => 'TMT', 'currency_symbol' => 'm', 'latitude' => 37.9601, 'longitude' => 58.3261],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'capital' => 'Abu Dhabi', 'currency' => 'AED', 'currency_symbol' => 'د.إ', 'latitude' => 24.4539, 'longitude' => 54.3773],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'capital' => 'Tashkent', 'currency' => 'UZS', 'currency_symbol' => "so'm", 'latitude' => 41.2995, 'longitude' => 69.2401],
            ['name' => 'Vietnam', 'code' => 'VN', 'capital' => 'Hanoi', 'currency' => 'VND', 'currency_symbol' => '₫', 'latitude' => 21.0285, 'longitude' => 105.8542],
            ['name' => 'Yemen', 'code' => 'YE', 'capital' => "Sana'a", 'currency' => 'YER', 'currency_symbol' => '﷼', 'latitude' => 15.3694, 'longitude' => 44.191],

            
            ['name' => 'Albania', 'code' => 'AL', 'capital' => 'Tirana', 'currency' => 'ALL', 'currency_symbol' => 'L', 'latitude' => 41.3275, 'longitude' => 19.8187],
            ['name' => 'Andorra', 'code' => 'AD', 'capital' => 'Andorra la Vella', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 42.5063, 'longitude' => 1.5218],
            ['name' => 'Austria', 'code' => 'AT', 'capital' => 'Vienna', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 48.2082, 'longitude' => 16.3738],
            ['name' => 'Belarus', 'code' => 'BY', 'capital' => 'Minsk', 'currency' => 'BYN', 'currency_symbol' => 'Br', 'latitude' => 53.9006, 'longitude' => 27.559],
            ['name' => 'Belgium', 'code' => 'BE', 'capital' => 'Brussels', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 50.8503, 'longitude' => 4.3517],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'capital' => 'Sarajevo', 'currency' => 'BAM', 'currency_symbol' => 'KM', 'latitude' => 43.8563, 'longitude' => 18.4131],
            ['name' => 'Bulgaria', 'code' => 'BG', 'capital' => 'Sofia', 'currency' => 'BGN', 'currency_symbol' => 'лв', 'latitude' => 42.6977, 'longitude' => 23.3219],
            ['name' => 'Croatia', 'code' => 'HR', 'capital' => 'Zagreb', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 45.815, 'longitude' => 15.9819],
            ['name' => 'Czechia', 'code' => 'CZ', 'capital' => 'Prague', 'currency' => 'CZK', 'currency_symbol' => 'Kč', 'latitude' => 50.0755, 'longitude' => 14.4378],
            ['name' => 'Denmark', 'code' => 'DK', 'capital' => 'Copenhagen', 'currency' => 'DKK', 'currency_symbol' => 'kr', 'latitude' => 55.6761, 'longitude' => 12.5683],
            ['name' => 'Estonia', 'code' => 'EE', 'capital' => 'Tallinn', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 59.437, 'longitude' => 24.7536],
            ['name' => 'Finland', 'code' => 'FI', 'capital' => 'Helsinki', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 60.1699, 'longitude' => 24.9384],
            ['name' => 'France', 'code' => 'FR', 'capital' => 'Paris', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 48.8566, 'longitude' => 2.3522],
            ['name' => 'Germany', 'code' => 'DE', 'capital' => 'Berlin', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 52.52, 'longitude' => 13.405],
            ['name' => 'Greece', 'code' => 'GR', 'capital' => 'Athens', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 37.9838, 'longitude' => 23.7275],
            ['name' => 'Hungary', 'code' => 'HU', 'capital' => 'Budapest', 'currency' => 'HUF', 'currency_symbol' => 'Ft', 'latitude' => 47.4979, 'longitude' => 19.0402],
            ['name' => 'Iceland', 'code' => 'IS', 'capital' => 'Reykjavik', 'currency' => 'ISK', 'currency_symbol' => 'kr', 'latitude' => 64.1466, 'longitude' => -21.9426],
            ['name' => 'Ireland', 'code' => 'IE', 'capital' => 'Dublin', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 53.3498, 'longitude' => -6.2603],
            ['name' => 'Italy', 'code' => 'IT', 'capital' => 'Rome', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 41.9028, 'longitude' => 12.4964],
            ['name' => 'Latvia', 'code' => 'LV', 'capital' => 'Riga', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 56.9496, 'longitude' => 24.1052],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'capital' => 'Vaduz', 'currency' => 'CHF', 'currency_symbol' => 'Fr', 'latitude' => 47.141, 'longitude' => 9.5209],
            ['name' => 'Lithuania', 'code' => 'LT', 'capital' => 'Vilnius', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 54.6872, 'longitude' => 25.2797],
            ['name' => 'Luxembourg', 'code' => 'LU', 'capital' => 'Luxembourg', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 49.6116, 'longitude' => 6.1319],
            ['name' => 'Malta', 'code' => 'MT', 'capital' => 'Valletta', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 35.8989, 'longitude' => 14.5146],
            ['name' => 'Moldova', 'code' => 'MD', 'capital' => 'Chisinau', 'currency' => 'MDL', 'currency_symbol' => 'L', 'latitude' => 47.0105, 'longitude' => 28.8638],
            ['name' => 'Monaco', 'code' => 'MC', 'capital' => 'Monaco', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 43.7384, 'longitude' => 7.4246],
            ['name' => 'Montenegro', 'code' => 'ME', 'capital' => 'Podgorica', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 42.4304, 'longitude' => 19.2594],
            ['name' => 'Netherlands', 'code' => 'NL', 'capital' => 'Amsterdam', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 52.3676, 'longitude' => 4.9041],
            ['name' => 'North Macedonia', 'code' => 'MK', 'capital' => 'Skopje', 'currency' => 'MKD', 'currency_symbol' => 'ден', 'latitude' => 41.9981, 'longitude' => 21.4254],
            ['name' => 'Norway', 'code' => 'NO', 'capital' => 'Oslo', 'currency' => 'NOK', 'currency_symbol' => 'kr', 'latitude' => 59.9139, 'longitude' => 10.7522],
            ['name' => 'Poland', 'code' => 'PL', 'capital' => 'Warsaw', 'currency' => 'PLN', 'currency_symbol' => 'zł', 'latitude' => 52.2297, 'longitude' => 21.0122],
            ['name' => 'Portugal', 'code' => 'PT', 'capital' => 'Lisbon', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 38.7223, 'longitude' => -9.1393],
            ['name' => 'Romania', 'code' => 'RO', 'capital' => 'Bucharest', 'currency' => 'RON', 'currency_symbol' => 'lei', 'latitude' => 44.4268, 'longitude' => 26.1025],
            ['name' => 'Russia', 'code' => 'RU', 'capital' => 'Moscow', 'currency' => 'RUB', 'currency_symbol' => '₽', 'latitude' => 55.7558, 'longitude' => 37.6173],
            ['name' => 'San Marino', 'code' => 'SM', 'capital' => 'San Marino', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 43.9424, 'longitude' => 12.4578],
            ['name' => 'Serbia', 'code' => 'RS', 'capital' => 'Belgrade', 'currency' => 'RSD', 'currency_symbol' => 'дин.', 'latitude' => 44.7866, 'longitude' => 20.4489],
            ['name' => 'Slovakia', 'code' => 'SK', 'capital' => 'Bratislava', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 48.1486, 'longitude' => 17.1077],
            ['name' => 'Slovenia', 'code' => 'SI', 'capital' => 'Ljubljana', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 46.0569, 'longitude' => 14.5058],
            ['name' => 'Spain', 'code' => 'ES', 'capital' => 'Madrid', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 40.4168, 'longitude' => -3.7038],
            ['name' => 'Sweden', 'code' => 'SE', 'capital' => 'Stockholm', 'currency' => 'SEK', 'currency_symbol' => 'kr', 'latitude' => 59.3293, 'longitude' => 18.0686],
            ['name' => 'Switzerland', 'code' => 'CH', 'capital' => 'Bern', 'currency' => 'CHF', 'currency_symbol' => 'Fr', 'latitude' => 46.948, 'longitude' => 7.4474],
            ['name' => 'Ukraine', 'code' => 'UA', 'capital' => 'Kyiv', 'currency' => 'UAH', 'currency_symbol' => '₴', 'latitude' => 50.4501, 'longitude' => 30.5234],
            ['name' => 'United Kingdom', 'code' => 'GB', 'capital' => 'London', 'currency' => 'GBP', 'currency_symbol' => '£', 'latitude' => 51.5074, 'longitude' => -0.1278],
            ['name' => 'Vatican City', 'code' => 'VA', 'capital' => 'Vatican City', 'currency' => 'EUR', 'currency_symbol' => '€', 'latitude' => 41.9029, 'longitude' => 12.4534],

            
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'capital' => "Saint John's", 'currency' => 'XCD', 'currency_symbol' => '$', 'latitude' => 17.1274, 'longitude' => -61.8468],
            ['name' => 'Argentina', 'code' => 'AR', 'capital' => 'Buenos Aires', 'currency' => 'ARS', 'currency_symbol' => '$', 'latitude' => -34.6037, 'longitude' => -58.3816],
            ['name' => 'Bahamas', 'code' => 'BS', 'capital' => 'Nassau', 'currency' => 'BSD', 'currency_symbol' => '$', 'latitude' => 25.0343, 'longitude' => -77.3963],
            ['name' => 'Barbados', 'code' => 'BB', 'capital' => 'Bridgetown', 'currency' => 'BBD', 'currency_symbol' => '$', 'latitude' => 13.1132, 'longitude' => -59.5988],
            ['name' => 'Belize', 'code' => 'BZ', 'capital' => 'Belmopan', 'currency' => 'BZD', 'currency_symbol' => '$', 'latitude' => 17.251, 'longitude' => -88.759],
            ['name' => 'Bolivia', 'code' => 'BO', 'capital' => 'Sucre', 'currency' => 'BOB', 'currency_symbol' => 'Bs.', 'latitude' => -19.0333, 'longitude' => -65.2627],
            ['name' => 'Brazil', 'code' => 'BR', 'capital' => 'Brasília', 'currency' => 'BRL', 'currency_symbol' => 'R$', 'latitude' => -15.8267, 'longitude' => -47.9218],
            ['name' => 'Canada', 'code' => 'CA', 'capital' => 'Ottawa', 'currency' => 'CAD', 'currency_symbol' => '$', 'latitude' => 45.4215, 'longitude' => -75.6972],
            ['name' => 'Chile', 'code' => 'CL', 'capital' => 'Santiago', 'currency' => 'CLP', 'currency_symbol' => '$', 'latitude' => -33.4489, 'longitude' => -70.6693],
            ['name' => 'Colombia', 'code' => 'CO', 'capital' => 'Bogotá', 'currency' => 'COP', 'currency_symbol' => '$', 'latitude' => 4.711, 'longitude' => -74.0721],
            ['name' => 'Costa Rica', 'code' => 'CR', 'capital' => 'San José', 'currency' => 'CRC', 'currency_symbol' => '₡', 'latitude' => 9.9281, 'longitude' => -84.0907],
            ['name' => 'Cuba', 'code' => 'CU', 'capital' => 'Havana', 'currency' => 'CUP', 'currency_symbol' => '$', 'latitude' => 23.1136, 'longitude' => -82.3666],
            ['name' => 'Dominica', 'code' => 'DM', 'capital' => 'Roseau', 'currency' => 'XCD', 'currency_symbol' => '$', 'latitude' => 15.301, 'longitude' => -61.3881],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'capital' => 'Santo Domingo', 'currency' => 'DOP', 'currency_symbol' => '$', 'latitude' => 18.4861, 'longitude' => -69.9312],
            ['name' => 'Ecuador', 'code' => 'EC', 'capital' => 'Quito', 'currency' => 'USD', 'currency_symbol' => '$', 'latitude' => -0.1807, 'longitude' => -78.4678],
            ['name' => 'El Salvador', 'code' => 'SV', 'capital' => 'San Salvador', 'currency' => 'USD', 'currency_symbol' => '$', 'latitude' => 13.6929, 'longitude' => -89.2182],
            ['name' => 'Grenada', 'code' => 'GD', 'capital' => "St. George's", 'currency' => 'XCD', 'currency_symbol' => '$', 'latitude' => 12.0561, 'longitude' => -61.7488],
            ['name' => 'Guatemala', 'code' => 'GT', 'capital' => 'Guatemala City', 'currency' => 'GTQ', 'currency_symbol' => 'Q', 'latitude' => 14.6349, 'longitude' => -90.5069],
            ['name' => 'Guyana', 'code' => 'GY', 'capital' => 'Georgetown', 'currency' => 'GYD', 'currency_symbol' => '$', 'latitude' => 6.8013, 'longitude' => -58.1551],
            ['name' => 'Haiti', 'code' => 'HT', 'capital' => 'Port-au-Prince', 'currency' => 'HTG', 'currency_symbol' => 'G', 'latitude' => 18.5944, 'longitude' => -72.3074],
            ['name' => 'Honduras', 'code' => 'HN', 'capital' => 'Tegucigalpa', 'currency' => 'HNL', 'currency_symbol' => 'L', 'latitude' => 14.0723, 'longitude' => -87.1921],
            ['name' => 'Jamaica', 'code' => 'JM', 'capital' => 'Kingston', 'currency' => 'JMD', 'currency_symbol' => '$', 'latitude' => 18.0179, 'longitude' => -76.8099],
            ['name' => 'Mexico', 'code' => 'MX', 'capital' => 'Mexico City', 'currency' => 'MXN', 'currency_symbol' => '$', 'latitude' => 19.4326, 'longitude' => -99.1332],
            ['name' => 'Nicaragua', 'code' => 'NI', 'capital' => 'Managua', 'currency' => 'NIO', 'currency_symbol' => 'C$', 'latitude' => 12.115, 'longitude' => -86.2362],
            ['name' => 'Panama', 'code' => 'PA', 'capital' => 'Panama City', 'currency' => 'PAB', 'currency_symbol' => 'B/.', 'latitude' => 8.9824, 'longitude' => -79.5199],
            ['name' => 'Paraguay', 'code' => 'PY', 'capital' => 'Asunción', 'currency' => 'PYG', 'currency_symbol' => '₲', 'latitude' => -25.2637, 'longitude' => -57.5759],
            ['name' => 'Peru', 'code' => 'PE', 'capital' => 'Lima', 'currency' => 'PEN', 'currency_symbol' => 'S/', 'latitude' => -12.0464, 'longitude' => -77.0428],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'capital' => 'Basseterre', 'currency' => 'XCD', 'currency_symbol' => '$', 'latitude' => 17.3026, 'longitude' => -62.7177],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'capital' => 'Castries', 'currency' => 'XCD', 'currency_symbol' => '$', 'latitude' => 14.0101, 'longitude' => -60.9875],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'capital' => 'Kingstown', 'currency' => 'XCD', 'currency_symbol' => '$', 'latitude' => 13.16, 'longitude' => -61.2248],
            ['name' => 'Suriname', 'code' => 'SR', 'capital' => 'Paramaribo', 'currency' => 'SRD', 'currency_symbol' => '$', 'latitude' => 5.852, 'longitude' => -55.2038],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'capital' => 'Port of Spain', 'currency' => 'TTD', 'currency_symbol' => '$', 'latitude' => 10.6549, 'longitude' => -61.5019],
            ['name' => 'United States', 'code' => 'US', 'capital' => 'Washington D.C.', 'currency' => 'USD', 'currency_symbol' => '$', 'latitude' => 38.9072, 'longitude' => -77.0369],
            ['name' => 'Uruguay', 'code' => 'UY', 'capital' => 'Montevideo', 'currency' => 'UYU', 'currency_symbol' => '$', 'latitude' => -34.9011, 'longitude' => -56.1645],
            ['name' => 'Venezuela', 'code' => 'VE', 'capital' => 'Caracas', 'currency' => 'VES', 'currency_symbol' => 'Bs.', 'latitude' => 10.4806, 'longitude' => -66.9036],

            
            ['name' => 'Australia', 'code' => 'AU', 'capital' => 'Canberra', 'currency' => 'AUD', 'currency_symbol' => 'A$', 'latitude' => -35.2809, 'longitude' => 149.13],
            ['name' => 'Fiji', 'code' => 'FJ', 'capital' => 'Suva', 'currency' => 'FJD', 'currency_symbol' => '$', 'latitude' => -18.1416, 'longitude' => 178.4419],
            ['name' => 'Kiribati', 'code' => 'KI', 'capital' => 'Tarawa', 'currency' => 'AUD', 'currency_symbol' => 'A$', 'latitude' => 1.3291, 'longitude' => 172.979],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'capital' => 'Majuro', 'currency' => 'USD', 'currency_symbol' => '$', 'latitude' => 7.1164, 'longitude' => 171.1858],
            ['name' => 'Micronesia', 'code' => 'FM', 'capital' => 'Palikir', 'currency' => 'USD', 'currency_symbol' => '$', 'latitude' => 6.9147, 'longitude' => 158.161],
            ['name' => 'Nauru', 'code' => 'NR', 'capital' => 'Yaren', 'currency' => 'AUD', 'currency_symbol' => 'A$', 'latitude' => -0.5228, 'longitude' => 166.9315],
            ['name' => 'New Zealand', 'code' => 'NZ', 'capital' => 'Wellington', 'currency' => 'NZD', 'currency_symbol' => '$', 'latitude' => -41.2865, 'longitude' => 174.7762],
            ['name' => 'Palau', 'code' => 'PW', 'capital' => 'Ngerulmud', 'currency' => 'USD', 'currency_symbol' => '$', 'latitude' => 7.5006, 'longitude' => 134.6242],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'capital' => 'Port Moresby', 'currency' => 'PGK', 'currency_symbol' => 'K', 'latitude' => -9.4438, 'longitude' => 147.1803],
            ['name' => 'Samoa', 'code' => 'WS', 'capital' => 'Apia', 'currency' => 'WST', 'currency_symbol' => 'T', 'latitude' => -13.8333, 'longitude' => -171.7667],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'capital' => 'Honiara', 'currency' => 'SBD', 'currency_symbol' => '$', 'latitude' => -9.428, 'longitude' => 159.9498],
            ['name' => 'Tonga', 'code' => 'TO', 'capital' => "Nuku'alofa", 'currency' => 'TOP', 'currency_symbol' => 'T$', 'latitude' => -21.1789, 'longitude' => -175.1982],
            ['name' => 'Tuvalu', 'code' => 'TV', 'capital' => 'Funafuti', 'currency' => 'AUD', 'currency_symbol' => 'A$', 'latitude' => -8.5211, 'longitude' => 179.1983],
            ['name' => 'Vanuatu', 'code' => 'VU', 'capital' => 'Port Vila', 'currency' => 'VUV', 'currency_symbol' => 'VT', 'latitude' => -17.7333, 'longitude' => 168.3273],
        ];
    }
}
